version: '2.4'

services:

  redis-service-test:
    image: redis:7.2-alpine
    command: redis-server --save "" --appendonly no
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5

  postgres-test:
    image: timescale/timescaledb:latest-pg15
    ports:
      - 5437:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Hello123!"
      POSTGRES_DB: "dataplane"
    volumes:
      - dataplane-postgres-test:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      retries: 5

  nats-test:
    image: nats:2.9-scratch
    command:
      - "--port"
      - "4222"

  mainapp-test:
    build:
      context: .
      dockerfile: docker-build/Dockerfile.main.alpine
    ports:
      - 9002:9002
    environment:
      DP_CODE_FOLDER: "/dataplane/code-files/"
      DP_DB_HOST: postgres-test
      DP_DB_USER: postgres
      DP_DB_SSL: "disable"
      DP_DB_PORT: "5432"
      DP_DB_DATABASE: "dataplane"
      secret_db_pwd: "Hello123!"
      DP_DATABASE: "timescaledb"
      DP_PORT: "9002"
      DP_NATS: "nats://nats-test:4222"
      DP_MODE: "development"
      DP_DEBUG: "true"
      DP_DB_DEBUG: "false"
      DP_MQ_DEBUG: "true"
      DP_METRIC_DEBUG: "false"
      DP_SCHEDULER_DEBUG: "false"
      DP_WORKER_DEBUG: "false"
      DP_CLEANTASKS_DAYS: "60"
      DP_REMOVELOGS_DAYS: "60"
      DP_CODE_FILE_STORAGE: "Database"
      DP_DFS_CODE_FOLDER: "/dataplane/dfs-code-files/"
      DP_DISTRIBUTED_MODE: "NO"
      DP_REDIS_HOST: "redis-service-test"
      DP_REDIS_PORT: "6379"
      DP_REDIS_PASSWORD: ""
      DP_REDIS_DB: "0"
      DP_PIPELINE_DATA_TTL_SECONDS: "3600"
      DP_PIPELINE_DATA_LIMIT_MB: "5"
      DP_ALLOW_ORIGINS: "http://localhost:9002"

  dataplane-worker:
    build:
      context: .
      dockerfile: docker-build/Dockerfile.workerpython.debian
    deploy:
      replicas: 2
      resources:
          limits:
            cpus: "0.5"
            memory: 1G
    environment:
      DP_CODE_FOLDER: "/dataplane/code-files/"
      DP_DB_HOST: postgres-test
      DP_DB_USER: postgres
      DP_DB_SSL: "disable"
      DP_DB_PORT: "5432"
      DP_DB_DATABASE: "dataplane"
      secret_db_pwd: "Hello123!"
      DP_DATABASE: "timescaledb"
      DP_NATS: "nats://nats-test:4222"
      DP_MODE: "development"
      DP_DEBUG: "true"
      DP_DB_DEBUG: "false"
      DP_MQ_DEBUG: "false"
      DP_METRIC_DEBUG: "false"
      DP_SCHEDULER_DEBUG: "false"
      DP_WORKER_HEARTBEAT_SECONDS: "1"
      DP_WORKER_GROUP: "python_dev"
      DP_WORKER_CMD: "/bin/sh"
      DP_WORKER_TYPE: "vm"
      DP_WORKER_LB: "roundrobin"
      DP_WORKER_ENV: "Development"
      DP_WORKER_PORT: "9005"
      DP_WORKER_LANGUAGES: "Python"
      DP_WORKER_LOAD_PACKAGES: "Python"
      DP_CODE_FILE_STORAGE: "Database"
      DP_DFS_CODE_FOLDER: "/dataplane/dfs-code-files/"
      DP_DISTRIBUTED_MODE: "NO"
      DP_REDIS_HOST: "redis-service-test"
      DP_REDIS_PORT: "6379"
      DP_REDIS_PASSWORD: ""
      DP_REDIS_DB: "0"

  dataplane-worker-prod:
    build:
      context: ./
      dockerfile: docker-build/Dockerfile.workerpython.debian
    deploy:
      replicas: 2
      resources:
          limits:
            cpus: "0.5"
            memory: 1G
    environment:
      DP_CODE_FOLDER: "/dataplane/code-files/"
      DP_DB_HOST: postgres-test
      DP_DB_USER: postgres
      DP_DB_SSL: "disable"
      DP_DB_PORT: "5432"
      DP_DB_DATABASE: "dataplane"
      secret_db_pwd: "Hello123!"
      DP_DATABASE: "timescaledb"
      DP_NATS: "nats://nats-test:4222"
      DP_MODE: "development"
      DP_DEBUG: "true"
      DP_DB_DEBUG: "false"
      DP_MQ_DEBUG: "true"
      DP_METRIC_DEBUG: "false"
      DP_SCHEDULER_DEBUG: "false"
      DP_WORKER_HEARTBEAT_SECONDS: "1"
      DP_WORKER_GROUP: "python_prod"
      DP_WORKER_CMD: "/bin/sh"
      DP_WORKER_TYPE: "vm"
      DP_WORKER_LB: "roundrobin"
      DP_WORKER_ENV: "Production"
      DP_WORKER_PORT: "9005"
      DP_WORKER_LANGUAGES: "Python"
      DP_WORKER_LOAD_PACKAGES: "Python"
      DP_CODE_FILE_STORAGE: "Database"
      DP_DFS_CODE_FOLDER: "/dataplane/dfs-code-files/"
      DP_DISTRIBUTED_MODE: "NO"
      DP_REDIS_HOST: "redis-service-test"
      DP_REDIS_PORT: "6379"
      DP_REDIS_PASSWORD: ""
      DP_REDIS_DB: "0"

volumes:
  dataplane-postgres-test:
