// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Environments struct {
	Name string `json:"name"`
}

type Pipelines struct {
	Name string `json:"name"`
}

type Workers struct {
	Name string `json:"name"`
}
