// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package privategraphql

type AddUsersInput struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	JobTitle  string `json:"job_title"`
	Password  string `json:"password"`
	Timezone  string `json:"timezone"`
}

type Environments struct {
	Name string `json:"name"`
}

type Pipelines struct {
	Name string `json:"name"`
}

type Workers struct {
	Name string `json:"name"`
}
