FROM node:16.10.0-bullseye-slim as builder2

RUN mkdir -p /node
RUN mkdir -p /node/app/mainapp/frontbuild

WORKDIR /node

ADD frontend/public /node/public
ADD frontend/src /node/src
ADD frontend/craco.config.js /node/craco.config.js
ADD frontend/package.json /node/package.json

RUN yarn add global env-cmd express
RUN yarn builddocker