FROM golang:1.17.3-bullseye

RUN apt update && apt install -y python3 python3-pip

RUN mkdir /workerfiles

WORKDIR /workerdev

COPY ./workers/go.mod /workerdev/go.mod

RUN go mod download

COPY python-example /workerfiles/python-example

RUN pip3 install -r /workerfiles/python-example/requirements.txt

CMD ["go","run","worker.go"]