FROM golang:1.17.3-bullseye

RUN apt update && apt install -y python3 python3-pip

RUN mkdir /workerfiles

WORKDIR /workerdev

COPY ./go.mod /workerdev/go.mod

RUN go mod download

RUN apt-get install -y sysstat

COPY examples/python-worker /workerfiles/python-worker

RUN pip3 install -r /workerfiles/python-worker/requirements.txt

CMD ["go","run","worker.go"]