FROM golang:1.17.3-buster

RUN go get -v golang.org/x/tools/gopls
# RUN go get github.com/uudashr/gopkgs/cmd/gopkgs@latest
RUN go get -u github.com/ramya-rao-a/go-outline
RUN go install github.com/go-delve/delve/cmd/dlv@latest
RUN go install honnef.co/go/tools/cmd/staticcheck@latest

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs && node -v
RUN npm install -g yarn n
RUN n 16.8.0

RUN yarn install --modules-folder ./frontend