// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package privategraphql

import (
	"time"
)

type AccessGroupsInput struct {
	AccessGroupID string `json:"AccessGroupID"`
	Name          string `json:"Name"`
	Description   string `json:"Description"`
	Active        bool   `json:"Active"`
	EnvironmentID string `json:"EnvironmentID"`
}

type AddEnvironmentInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type AddPreferencesInput struct {
	Preference string `json:"preference"`
	Value      string `json:"value"`
}

type AddSecretsInput struct {
	Secret        string  `json:"Secret"`
	Description   *string `json:"Description"`
	Value         string  `json:"Value"`
	EnvironmentID string  `json:"EnvironmentId"`
	Active        bool    `json:"Active"`
}

type AddUpdateMeInput struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	JobTitle  string `json:"job_title"`
	Timezone  string `json:"timezone"`
}

type AddUsersInput struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	JobTitle  string `json:"job_title"`
	Password  string `json:"password"`
	Timezone  string `json:"timezone"`
}

type ChangePasswordInput struct {
	Password string `json:"password"`
	UserID   string `json:"user_id"`
}

type Data struct {
	Language string `json:"language"`
}

type DataInput struct {
	Language string `json:"language"`
}

type PipelineEdges struct {
	EdgeID        string             `json:"edgeID"`
	PipelineID    string             `json:"pipelineID"`
	From          string             `json:"from"`
	To            string             `json:"to"`
	EnvironmentID string             `json:"environmentID"`
	Meta          *PipelineEdgesMeta `json:"meta"`
	Active        bool               `json:"active"`
}

type PipelineEdgesInput struct {
	EdgeID        string                  `json:"edgeID"`
	PipelineID    string                  `json:"pipelineID"`
	From          string                  `json:"from"`
	To            string                  `json:"to"`
	EnvironmentID string                  `json:"environmentID"`
	Meta          *PipelineEdgesMetaInput `json:"meta"`
}

type PipelineEdgesMeta struct {
	SourceHandle  string `json:"sourceHandle"`
	TargetHandle  string `json:"targetHandle"`
	EdgeType      string `json:"edgeType"`
	ArrowHeadType string `json:"arrowHeadType"`
}

type PipelineEdgesMetaInput struct {
	SourceHandle  string `json:"sourceHandle"`
	TargetHandle  string `json:"targetHandle"`
	EdgeType      string `json:"edgeType"`
	ArrowHeadType string `json:"arrowHeadType"`
}

type PipelineFlow struct {
	Edges []*PipelineEdges `json:"edges"`
	Nodes []*PipelineNodes `json:"nodes"`
}

type PipelineFlowInput struct {
	NodesInput []*PipelineNodesInput `json:"nodesInput"`
	EdgesInput []*PipelineEdgesInput `json:"edgesInput"`
}

type PipelineNodes struct {
	NodeID        string             `json:"nodeID"`
	PipelineID    string             `json:"pipelineID"`
	Name          string             `json:"name"`
	EnvironmentID string             `json:"environmentID"`
	NodeType      string             `json:"nodeType"`
	Description   string             `json:"description"`
	Meta          *PipelineNodesMeta `json:"meta"`
	Active        bool               `json:"active"`
}

type PipelineNodesInput struct {
	NodeID        string                  `json:"nodeID"`
	PipelineID    string                  `json:"pipelineID"`
	Name          string                  `json:"name"`
	EnvironmentID string                  `json:"environmentID"`
	NodeType      string                  `json:"nodeType"`
	Description   string                  `json:"description"`
	Meta          *PipelineNodesMetaInput `json:"meta"`
}

type PipelineNodesMeta struct {
	Position *Position `json:"position"`
	Data     *Data     `json:"data"`
}

type PipelineNodesMetaInput struct {
	Position *PositionInput `json:"position"`
	Data     *DataInput     `json:"data"`
}

type Platform struct {
	ID           string `json:"id"`
	BusinessName string `json:"business_name"`
	Timezone     string `json:"timezone"`
	Complete     bool   `json:"complete"`
}

type Position struct {
	X int `json:"x"`
	Y int `json:"y"`
}

type PositionInput struct {
	X int `json:"x"`
	Y int `json:"y"`
}

type Preferences struct {
	Preference string `json:"preference"`
	Value      string `json:"value"`
}

type UpdateEnvironment struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type UpdateSecretsInput struct {
	Secret        string  `json:"Secret"`
	Description   *string `json:"Description"`
	EnvironmentID string  `json:"EnvironmentId"`
	Active        bool    `json:"Active"`
}

type UpdateUsersInput struct {
	UserID    string `json:"user_id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	JobTitle  string `json:"job_title"`
	Timezone  string `json:"timezone"`
}

type WorkerGroup struct {
	WorkerGroup string    `json:"WorkerGroup"`
	Status      string    `json:"Status"`
	T           time.Time `json:"T"`
	Interval    int       `json:"Interval"`
	Env         string    `json:"Env"`
	Lb          string    `json:"LB"`
	WorkerType  string    `json:"WorkerType"`
}

type Workers struct {
	WorkerGroup string    `json:"WorkerGroup"`
	WorkerID    string    `json:"WorkerID"`
	Status      string    `json:"Status"`
	T           time.Time `json:"T"`
	Interval    int       `json:"Interval"`
	CPUPerc     float64   `json:"CPUPerc"`
	Load        float64   `json:"Load"`
	MemoryPerc  float64   `json:"MemoryPerc"`
	MemoryUsed  float64   `json:"MemoryUsed"`
	Env         string    `json:"Env"`
	Lb          string    `json:"LB"`
	WorkerType  string    `json:"WorkerType"`
}

type UpdatePlatformInput struct {
	ID           string `json:"id"`
	BusinessName string `json:"business_name"`
	Timezone     string `json:"timezone"`
	Complete     bool   `json:"complete"`
}
