// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package desktopgraphql

type Environments struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Active      *bool   `json:"active"`
}
